# -*- coding: utf-8 -*-
"""Alura_Store_Larissa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZ2RcDxkic45hIJcpC8D4FjDX47fYfXY

# **Projeto Alura Store - Decisão de negócio com Dados.**

Neste projeto irei ajudar o Senhor João a decidir qual loja da sua rede Alura Store vender para iniciar um novo empreendimento. Para isso, irei analisará dados de vendas, desempenho e avaliações das 4 lojas fictícias da Alura Store. O objetivo é identificar a loja com menor eficiência e apresentar uma recomendação final baseada nos dados.

O que irei realizar:
- Carregar e manipular dados CSV com a biblioteca Pandas;
- Criar visualizações de dados com biblioteca Matplotlib;
- Analisar métricas como faturamento, avaliações e desempenho de vendas;
- Apresentar uma recomendação.
"""



"""### **Base de dados**

Os dados de cada loja estão disponíveis nos arquivos CSV e serão carregados utilizando o código base já fornecido. O código extrai informações das quatro lojas e organiza os dados em DataFrames utilizando a biblioteca Pandas.
"""



"""###**Importação e conhecimento da base de dados**

O primeiro passo que realizei foi a importação da base de dados e verificar algumas características gerais, como:

*   Quantidade de linhas e colunas;
*   Quais as colunas da base de dados;
*   Explorar as diferentes colunas existentes;
*   Verificar os tipos dos dados;
*   Verificar se possui dados nulos.






"""



import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_1.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_4.csv"

loja1 = pd.read_csv(url)
loja2 = pd.read_csv(url2)
loja3 = pd.read_csv(url3)
loja4 = pd.read_csv(url4)

loja1.head()

"""**Loja 01**"""

type(loja1)

loja1.shape
# Linhas e colunas.

loja1.columns

loja1.info()

loja1.describe()

loja1.isnull().sum()
# Identificação de dados nulos.



"""**Loja 02**"""

type(loja2)

loja2.shape
# Linhas e colunas.

loja2.columns

loja2.info()

loja2.describe()

loja2.isnull().sum()
# Identificação de dados nulos.



"""**Loja 03**"""

type(loja3)

loja3.shape
# Linhas e colunas.

loja3.columns

loja3.info()

loja3.describe()

loja3.isnull().sum()
# Identificação de dados nulos.



"""**Loja 04**"""

type(loja4)

loja4.shape
# Linhas e colunas.

loja4.columns

loja4.info()

loja4.describe()

loja4.isnull().sum()
# Identificação de dados nulos.



"""### **Análise do faturamento**

Nesta primeira análise, vou calcular o faturamento total de cada loja. Somando os valores da coluna Preço de cada loja para estimar o faturamento.




"""

faturamento_total_lj1 = loja1["Preço"].sum()
faturamento_total_lj1

faturamento_total_lj2 = loja2["Preço"].sum()
faturamento_total_lj2

faturamento_total_lj3 = loja3["Preço"].sum()
faturamento_total_lj3

faturamento_total_lj4 = loja4["Preço"].sum()
faturamento_total_lj4



"""### **Concatenação e criação de colunas**"""

loja1["Loja_id"] = "Loja 1"

loja2["Loja_id"] = "Loja 2"

loja3["Loja_id"] = "Loja 3"

loja4["Loja_id"] = "Loja 4"



# Juntar todos em um único DataFrame
lojas = pd.concat([loja1, loja2, loja3, loja4])

lojas.head()





"""### **Vendas por Categoria**

Neste passo, vou calcular a quantidade de produtos vendidos por categoria em cada loja. A ideia é agrupar os dados por categoria e contar o número de vendas de cada tipo, mostrando as categoria mais populares de cada loja
"""

# Agrupar por Loja e Categoria, contando quantos produtos foram vendidos
quant_vendida = (lojas.groupby(['Loja_id', 'Categoria do Produto']).size().reset_index(name='Quantidade_Vendida'))

# Ordena dentro de cada loja para ver as categorias mais populares
quant_vendida = quant_vendida.sort_values(['Loja_id', 'Quantidade_Vendida'], ascending=[True, False])

print(quant_vendida)

# Categoria mais e menos vendada de cada loja.
# Agrupar por categoria e loja
quant_vendida = lojas.groupby(['Categoria do Produto', 'Loja_id']).size().reset_index(name='Quantidade_Vendida')

# Ordenar dentro de cada categoria (maior → menor)
quant_vendida = quant_vendida.sort_values(['Categoria do Produto', 'Quantidade_Vendida'], ascending=[True, False])

# Mostrar o ranking por categoria
for cat in quant_vendida['Categoria do Produto'].unique():
    df_cat = quant_vendida[quant_vendida['Categoria do Produto'] == cat]
    loja_mais = df_cat.iloc[0]
    loja_menos = df_cat.iloc[-1]

    print(f"\n Categoria: {cat}")
    print(f" Loja que mais vendeu: {loja_mais['Loja_id']} ({loja_mais['Quantidade_Vendida']} vendas)")
    print(f" Loja que menos vendeu: {loja_menos['Loja_id']} ({loja_menos['Quantidade_Vendida']} vendas)")



"""### **Média de Avaliação das Lojas**

Neste passo, vou calcular a média das avaliações dos clientes para cada loja. O objetivo é entender a satisfação dos clientes com os produtos vendidos.

"""

lojas.head()

# Calcular a média das avaliações por loja.

media_avaliacao = lojas.groupby('Loja_id')['Avaliação da compra'].mean().reset_index(name='Média Avaliação')
print(media_avaliacao)



# Loja com melhor avaliação para a pior
media_avaliacao = media_avaliacao.sort_values('Média Avaliação', ascending=False)
print(media_avaliacao)



"""### **Produtos Mais e Menos Vendidos.**

Neste passo, irei identificar quais produtos foram os mais vendidos e os menos vendidos em cada loja.  Ao final, visualizei os resultados de forma que fique claro quais produtos se destacaram nas vendas de cada loja.

1.   Item da lista
2.   Item da lista


"""

lojas.info()

# Agrupa os dados por loja e produto, contando quantas vezes cada produto foi vendido
vendas_por_produto = (lojas.groupby(['Loja_id', 'Categoria do Produto']).size().reset_index(name='Quantidade_vendida'))
print(vendas_por_produto)

# Ordena dentro de cada loja (do mais vendido para o menos vendido)
vendas_por_produto = vendas_por_produto.sort_values('Quantidade_vendida', ascending=False)
print(vendas_por_produto.head())

# Produto mais vendido por loja.
mais_vendidos = vendas_por_produto.groupby('Loja_id').head(1).reset_index(drop=True)
print(mais_vendidos)

# Produto menos vendido por loja.
menos_vendidos = vendas_por_produto.groupby('Loja_id').tail(1).reset_index(drop=True)
print(menos_vendidos)

# Qual loja mais e menos vendeu
vendas_por_loja = lojas.groupby('Loja_id').size().reset_index(name='Total_vendas')
print(vendas_por_loja)

"""### **Frete Médio por Loja.**

Neste passo, irei calcular o custo médio de frete para cada loja. O objetivo é entender quanto, em média, está sendo gasto com frete para cada uma das lojas. Sabendo que o cliente que paga o frete.
"""

lojas.info()

# Frete médio por loja
media_frete = lojas.groupby('Loja_id')['Frete'].mean().reset_index(name='Frete_médio')
print(media_frete)



"""### **Gráficos.**"""

pip install matplotlib



# Faturamento total de todas as lojas.
faturamento_lojas = (lojas.groupby('Loja_id')['Preço'].sum().reset_index(name='Faturamento_Total'))
print(faturamento_lojas)

# Faturamento total das lojas.

import matplotlib.pyplot as plt

Lojas = ['Loja 1', 'Loja 2', 'Loja 3', 'Loja 4']
Faturamento_Total = [1534509.12, 1488459.06, 1464025.03, 1384497.58]

plt.plot(Lojas, Faturamento_Total, marker='o', color='steelblue', linewidth=2)
plt.title('Faturamento Total das Lojas')
plt.xlabel('Lojas')
plt.ylabel('Faturamento em R$')
plt.grid(True)
plt.show()

# marker='o': adiciona marcadores nos pontos (para facilitar a leitura).
# color='steelblue': define a cor da linha.
# linewidth=2: aumenta a espessura da linha.
# plt.grid(True): adiciona uma grade para facilitar a visualização dos valores.



media_avaliacao = lojas.groupby('Loja_id')['Avaliação da compra'].mean().reset_index(name='Média Avaliação')
print(media_avaliacao)

# Média de avaliações de acordo com cada loja.

import matplotlib.pyplot as plt

plt.bar(media_avaliacao['Loja_id'], media_avaliacao['Média Avaliação'], color='steelblue')
plt.title('Média de Avaliações por Loja')
plt.xlabel('Lojas')
plt.ylabel('Média das Avaliações')

# Adicionar os valores em cima das barras
for i, valor in enumerate(media_avaliacao['Média Avaliação']):
    plt.text(i, valor + 0.05, f'{valor:.2f}', ha='center')

plt.show()

# plt.barh() → cria barras verticais.
# color='steelblue' → define a cor das barras.





import matplotlib.pyplot as plt
import seaborn as sns  # facilita o gráfico agrupado

# Gráfico de barras agrupadas
plt.figure(figsize=(12,6))
sns.barplot(data=vendas_por_produto, x='Categoria do Produto', y='Quantidade_vendida', hue='Loja_id', palette='Blues')

plt.title('Vendas por Categoria e Loja')
plt.xlabel('Categoria do Produto')
plt.ylabel('Quantidade Vendida')
plt.legend(title='Loja')
plt.grid(True, axis='y')
plt.show()



media_frete = lojas.groupby('Loja_id')['Frete'].mean().reset_index(name='Frete_médio')
print(media_frete)

# Frete médio por loja

import matplotlib.pyplot as plt


plt.barh(media_frete['Loja_id'], media_frete['Frete_médio'], color='steelblue')
plt.title('Frete médio por loja')
plt.xlabel('Valor médio do frete (R$)')
plt.ylabel('Lojas')

# Adicionar os valores no final de cada barra
for i, valor in enumerate(media_frete['Frete_médio']):
    plt.text(valor, i, f'{valor:.2f}', va='center')  # "valor + 10" afasta o texto da barra

plt.show()

# plt.barh() → cria barras horizontais.
# color='steelblue' → define a cor das barras.
# plt.grid(True) → adiciona uma grade de fundo para facilitar a leitura.



"""### **Relátorio**

## Relatório Final — Análise das Lojas do Senhor João

O objetivo desta análise foi identificar qual loja o Senhor João deve vender, com base em indicadores financeiros, de desempenho de vendas e de satisfação dos clientes. Foram analisados:  
- O faturamento total de cada loja;  
- As categorias de produtos mais e menos vendidas;  
- A média das avaliações dos clientes;  
- Os produtos mais e menos vendidos;  
- O frete médio por loja.  

A partir dessas informações, foi possível comparar o desempenho geral de cada unidade e recomendar aquela que apresenta os piores resultados para uma eventual venda.


## Desenvolvimento das Análises

### Faturamento Total
- Maior faturamento: Loja 1 - R$ 1.534.509,12

- Menor faturamento: Loja 4 - R$ 1.384.497,58  

A Loja 1 apresentou o melhor desempenho financeiro, enquanto a Loja 4 teve o menor faturamento total, indicando menor volume de vendas ou ticket médio mais baixo.


### Categorias de Produtos Mais e Menos Vendidas
| Categoria             | Loja que Mais Vendeu | Loja que Menos Vendeu |
| --------------------- | -------------------- | --------------------- |
| Brinquedos            | Loja 4 (338)         | Loja 2 (313)          |
| Eletrodomésticos      | Loja 1 (312)         | Loja 4 (254)          |
| Eletrônicos           | Loja 3 (451)         | Loja 2 (422)          |
| Esporte e Lazer       | Loja 1 (284)         | Loja 2 (275)          |
| Instrumentos Musicais | Loja 2 (224)         | Loja 4 (170)          |
| Livros                | Loja 2 (197)         | Loja 1 (173)          |
| Móveis                | Loja 3 (499)         | Loja 2 (442)          |
| Utilidades Domésticas | Loja 4 (201)         | Loja 1 (171)          |

As Lojas 1 e 3 se destacam em várias categorias com bom desempenho em eletrodomésticos, esportes e móveis.
Já a Loja 2 tem resultados medianos, mas se destaca em instrumentos musicais e livros.
A Loja 4 aparece com menor desempenho em múltiplas categorias, especialmente em eletrodomésticos e instrumentos musicais.


### Média das Avaliações dos Clientes

- Melhor avaliada: Loja 3 — 4,04  
- Pior avaliada: Loja 1 — 3,97  

A Loja 3 se sobressai na satisfação dos clientes, com avaliações médias mais altas. Apesar do bom faturamento, a Loja 1 apresenta a pior média de avaliação.


### Produtos Mais e Menos Vendidos
- Mais vendidos: Lojas 1, 2 e 3 — 2.359 unidades  
- Menos vendidos: Loja 4 — 2.358 unidades  

Mesmo com diferença pequena, a Loja 4 novamente aparece na última posição, reforçando o padrão de desempenho mais baixo em volume de vendas.


### Frete Médio por Loja
- Maior frete: Loja 1 — R$ 34,60  

- Menor frete: Loja 4 — R$ 31,20  

A Loja 1 apresenta o maior custo médio de frete. Já a Loja 4 tem o menor custo logístico.


## Síntese Comparativa

| Indicador | Melhor Desempenho | Pior Desempenho |
|------------|-------------------|-----------------|
| **Faturamento** | Loja 1 | Loja 4 |
| **Categorias vendidas** | Loja 3 | Loja 4 |
| **Avaliação dos clientes** | Loja 3 | Loja 1 |
| **Produtos vendidos** | Lojas 1, 2, 3 | Loja 4 |
| **Frete médio** | Loja 4 | Loja 1 |


## Conclusão e Recomendação

Com base em todos os indicadores analisados, a Loja 4 apresenta o pior desempenho geral, pois:

- Possui menor faturamento total (R$ 1.384.497,58);  
- Registra menor volume de categorias e produtos vendidos;  
- Apesar de ter o menor frete médio, isso não se reflete em lucro ou competitividade;  
- Não lidera em nenhum dos indicadores positivos, mostrando resultados consistentes abaixo das demais.

Portanto, recomenda-se que o Senhor João venda a Loja 4, por ser a unidade menos rentável e com menor potencial de crescimento, permitindo concentrar esforços e recursos nas lojas com melhor desempenho (especialmente a Loja 3, que combina boas vendas, boa avaliação e mix de produtos sólido).
"""



"""### **Extra**"""

import matplotlib.pyplot as plt

# Gráfico de dispersão com latitude e longitude
plt.figure(figsize=(15,6)) # Tamanho da figura

for loja in lojas['Loja_id'].unique():
    df_loja = lojas[lojas['Loja_id'] == loja]  # Filtra apenas os dados da loja
    plt.scatter(df_loja['lon'], df_loja['lat'], label=loja, alpha=0.6) # Pontos

plt.title('Distribuição Geográfica das Vendas por Loja')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.legend()
plt.show()

import folium
from folium.plugins import HeatMap

mapa_calor = folium.Map(location=[lojas['lat'].mean(), lojas['lon'].mean()], zoom_start=4)
HeatMap(data=lojas[['lat', 'lon']]).add_to(mapa_calor)
mapa_calor





